from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QListWidget, QDialog
from PyQt6.QtCore import Qt, QMimeData
from PyQt6.QtGui import QDrag
import enchant

class SpellCorrectingLineEdit(QtWidgets.QLineEdit):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.spell_checker = enchant.Dict("ru_RU")

    def focusOutEvent(self, event):
        text = self.text()
        if text.strip():
            words = text.split(' ')
            corrected_words = [self.spell_checker.suggest(word)[0] if self.spell_checker.suggest(word) else word for word in words]
            corrected_text = ' '.join(corrected_words)
            self.setText(corrected_text)
        super().focusOutEvent(event)

class DragDropTrainerListWidget(QListWidget):
    def __init__(self):
        super().__init__()

        # Разрешаем возможность перетаскивания элементов
        self.setDragEnabled(True)
      
    def startDrag(self, supportedActions):
        # При начале перетаскивания создаем объект QMimeData
        mimeData = QMimeData()

        # Устанавливаем данные для перетаскивания (в данном случае, текст элемента)
        item = self.currentItem()
        mimeData.setText(item.text()  + ' - ')

        # Создаем объект QDrag и начинаем операцию перетаскивания
        drag = QDrag(self)
        drag.setMimeData(mimeData)
        
        drag.exec(Qt.DropAction.MoveAction)

class DragDropWorkoutListWidget(QListWidget):
    def __init__(self):
        super().__init__()

        self.setDragEnabled(True)

    def startDrag(self, supportedActions):
        mimeData = QMimeData()

        item = self.currentItem()
        mimeData.setText(item.text())

        drag = QDrag(self)
        drag.setMimeData(mimeData)
        drag.exec(Qt.DropAction.MoveAction)

class ModalDialog(QDialog):
    def __init__(self, parent=None):
        super(ModalDialog, self).__init__(parent)

        self.setWindowTitle("Модальное окно")
        self.setGeometry(400, 250, 400, 100)
        self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)

        layout = QtWidgets.QVBoxLayout()
        
        # Добавляем метку с текстом
        label = QtWidgets.QLabel("Таблица перенесена в Excel, можете закрыть приложение", self)
        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(label)

        # Добавляем кнопку для закрытия модального окна
        close_button = QtWidgets.QPushButton("ОК", self)
        close_button.clicked.connect(self.close)
        layout.addWidget(close_button)

        self.setLayout(layout)

class ExceptModalDialog(QDialog):
    def __init__(self, parent=None):
        super(ExceptModalDialog, self).__init__(parent)

        self.setWindowTitle("Модальное окно")
        self.setGeometry(400, 250, 400, 100)
        self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)

        layout = QtWidgets.QVBoxLayout()
        
        # Добавляем метку с текстом
        label = QtWidgets.QLabel("Проверьте правильность заполнения полей 'Месяц' и 'Зал'", self)
        label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(label)

        # Добавляем кнопку для закрытия модального окна
        close_button = QtWidgets.QPushButton("ОК", self)
        close_button.clicked.connect(self.close)
        layout.addWidget(close_button)

        self.setLayout(layout)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.Window | 
                                  QtCore.Qt.WindowType.WindowMinMaxButtonsHint | 
                                  QtCore.Qt.WindowType.WindowMaximizeButtonHint | 
                                  QtCore.Qt.WindowType.WindowMinimizeButtonHint | 
                                  QtCore.Qt.WindowType.WindowCloseButtonHint)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/Creator/icons/icon.svg"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLabel {\n"                            
"    font-weight: bold;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #70A6469F;\n"
"    color: #FFFFE8FF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #69A6469F;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color: #FFA6469F;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #4AA6469F;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #30A6469F;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #69A6469F;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    background-color: #4AA6469F;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    background-color: #30A6469F;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #69A6469F;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4AA6469F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #30A6469F;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #FF702F6B;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #E3702F6B;\n"
"    font-family: Rubik;\n"
"    border-radius: 5%;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.done_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.done_btn.setStyleSheet("")
        self.done_btn.setObjectName("done_btn")
        self.done_btn.setToolTip("Для активации кнопки заполните поля 'Месяц' и 'Зал'")
        self.done_btn.setEnabled(False)
        self.done_btn.clicked.connect(self.write_cells)
        #self.done_btn.clicked.connect(self.open_modal_dialog)
        self.gridLayout_2.addWidget(self.done_btn, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sunday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_20_textEdit.setSizePolicy(sizePolicy)
        self.sunday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_20_textEdit.setObjectName("sunday_20_textEdit")
        self.gridLayout.addWidget(self.sunday_20_textEdit, 13, 7, 1, 1)
        self.saturday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_19_textEdit.setSizePolicy(sizePolicy)
        self.saturday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_19_textEdit.setObjectName("saturday_19_textEdit")
        self.gridLayout.addWidget(self.saturday_19_textEdit, 12, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_20.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 13, 0, 1, 1)
        self.saturday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_20_textEdit.setSizePolicy(sizePolicy)
        self.saturday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_20_textEdit.setObjectName("saturday_20_textEdit")
        self.gridLayout.addWidget(self.saturday_20_textEdit, 13, 6, 1, 1)
        self.sunday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_18_textEdit.setSizePolicy(sizePolicy)
        self.sunday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_18_textEdit.setObjectName("sunday_18_textEdit")
        self.gridLayout.addWidget(self.sunday_18_textEdit, 11, 7, 1, 1)
        self.wednesday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_20_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_20_textEdit.setObjectName("wednesday_20_textEdit")
        self.gridLayout.addWidget(self.wednesday_20_textEdit, 13, 3, 1, 1)
        self.tuesday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_19_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_19_textEdit.setObjectName("tuesday_19_textEdit")
        self.gridLayout.addWidget(self.tuesday_19_textEdit, 12, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_19.setAcceptDrops(True)
        self.label_19.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 12, 0, 1, 1)
        self.monday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_19_textEdit.setSizePolicy(sizePolicy)
        self.monday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_19_textEdit.setObjectName("monday_19_textEdit")
        self.gridLayout.addWidget(self.monday_19_textEdit, 12, 1, 1, 1)
        self.thursday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_20_textEdit.setSizePolicy(sizePolicy)
        self.thursday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_20_textEdit.setObjectName("thursday_20_textEdit")
        self.gridLayout.addWidget(self.thursday_20_textEdit, 13, 4, 1, 1)
        self.thursday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_19_textEdit.setSizePolicy(sizePolicy)
        self.thursday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_19_textEdit.setObjectName("thursday_19_textEdit")
        self.gridLayout.addWidget(self.thursday_19_textEdit, 12, 4, 1, 1)
        self.trainer_list = DragDropTrainerListWidget()
        self.trainer_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.trainer_list.setDragEnabled(True)
        self.trainer_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragOnly)
        self.trainer_list.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.trainer_list.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.trainer_list.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.trainer_list.setObjectName("trainer_list")
        self.gridLayout.addWidget(self.trainer_list, 14, 0, 1, 4)
        self.monday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_20_textEdit.setSizePolicy(sizePolicy)
        self.monday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_20_textEdit.setObjectName("monday_20_textEdit")
        self.gridLayout.addWidget(self.monday_20_textEdit, 13, 1, 1, 1)
        self.friday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_20_textEdit.setSizePolicy(sizePolicy)
        self.friday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_20_textEdit.setObjectName("friday_20_textEdit")
        self.gridLayout.addWidget(self.friday_20_textEdit, 13, 5, 1, 1)
        self.monday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_11_textEdit.setSizePolicy(sizePolicy)
        self.monday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_11_textEdit.setObjectName("monday_11_textEdit")
        self.gridLayout.addWidget(self.monday_11_textEdit, 5, 1, 1, 1)
        self.friday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_10_textEdit.setSizePolicy(sizePolicy)
        self.friday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_10_textEdit.setObjectName("friday_10_textEdit")
        self.gridLayout.addWidget(self.friday_10_textEdit, 4, 5, 1, 1)
        self.wednesday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_11_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_11_textEdit.setObjectName("wednesday_11_textEdit")
        self.gridLayout.addWidget(self.wednesday_11_textEdit, 5, 3, 1, 1)
        self.tuesday_20_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_20_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_20_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_20_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_20_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_20_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_20_textEdit.setObjectName("tuesday_20_textEdit")
        self.gridLayout.addWidget(self.tuesday_20_textEdit, 13, 2, 1, 1)
        self.saturday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_18_textEdit.setSizePolicy(sizePolicy)
        self.saturday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_18_textEdit.setObjectName("saturday_18_textEdit")
        self.gridLayout.addWidget(self.saturday_18_textEdit, 11, 6, 1, 1)
        self.friday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_19_textEdit.setSizePolicy(sizePolicy)
        self.friday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_19_textEdit.setObjectName("friday_19_textEdit")
        self.gridLayout.addWidget(self.friday_19_textEdit, 12, 5, 1, 1)
        self.workout_list = DragDropWorkoutListWidget()
        self.workout_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.workout_list.setDragEnabled(True)
        self.workout_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragOnly)
        self.workout_list.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.workout_list.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.workout_list.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.workout_list.setObjectName("workout_list")
        self.gridLayout.addWidget(self.workout_list, 14, 4, 1, 4)
        self.wednesday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_19_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_19_textEdit.setObjectName("wednesday_19_textEdit")
        self.gridLayout.addWidget(self.wednesday_19_textEdit, 12, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_12.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.sunday_19_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_19_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_19_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_19_textEdit.setSizePolicy(sizePolicy)
        self.sunday_19_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_19_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_19_textEdit.setObjectName("sunday_19_textEdit")
        self.gridLayout.addWidget(self.sunday_19_textEdit, 12, 7, 1, 1)
        self.wednesday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_12_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_12_textEdit.setObjectName("wednesday_12_textEdit")
        self.gridLayout.addWidget(self.wednesday_12_textEdit, 6, 3, 1, 1)
        self.monday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_10_textEdit.setSizePolicy(sizePolicy)
        self.monday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_10_textEdit.setObjectName("monday_10_textEdit")
        self.gridLayout.addWidget(self.monday_10_textEdit, 4, 1, 1, 1)
        self.thursday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_10_textEdit.setSizePolicy(sizePolicy)
        self.thursday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_10_textEdit.setObjectName("thursday_10_textEdit")
        self.gridLayout.addWidget(self.thursday_10_textEdit, 4, 4, 1, 1)
        self.tuesday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.tuesday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.tuesday_label.setObjectName("tuesday_label")
        self.gridLayout.addWidget(self.tuesday_label, 3, 2, 1, 1)
        self.friday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.friday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.friday_label.setObjectName("friday_label")
        self.gridLayout.addWidget(self.friday_label, 3, 5, 1, 1)
        self.wednesday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.wednesday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.wednesday_label.setObjectName("wednesday_label")
        self.gridLayout.addWidget(self.wednesday_label, 3, 3, 1, 1)
        self.wednesday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_10_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_10_textEdit.setObjectName("wednesday_10_textEdit")
        self.gridLayout.addWidget(self.wednesday_10_textEdit, 4, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_10.setAcceptDrops(False)
        self.label_10.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.sunday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_10_textEdit.setSizePolicy(sizePolicy)
        self.sunday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_10_textEdit.setObjectName("sunday_10_textEdit")
        self.gridLayout.addWidget(self.sunday_10_textEdit, 4, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_11.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.month_edit = SpellCorrectingLineEdit(parent=self.centralwidget)
        self.month_edit.setInputMask("")
        self.month_edit.setText("")
        self.month_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.month_edit.setObjectName("month_edit")
        self.month_edit.textChanged.connect(self.check_inputs)
        self.gridLayout.addWidget(self.month_edit, 1, 3, 1, 2)
        self.sunday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_12_textEdit.setSizePolicy(sizePolicy)
        self.sunday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_12_textEdit.setObjectName("sunday_12_textEdit")
        self.gridLayout.addWidget(self.sunday_12_textEdit, 6, 7, 1, 1)
        self.friday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_16_textEdit.setSizePolicy(sizePolicy)
        self.friday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_16_textEdit.setObjectName("friday_16_textEdit")
        self.gridLayout.addWidget(self.friday_16_textEdit, 9, 5, 1, 1)
        self.sunday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_17_textEdit.setSizePolicy(sizePolicy)
        self.sunday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_17_textEdit.setObjectName("sunday_17_textEdit")
        self.gridLayout.addWidget(self.sunday_17_textEdit, 10, 7, 1, 1)
        self.saturday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_17_textEdit.setSizePolicy(sizePolicy)
        self.saturday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_17_textEdit.setObjectName("saturday_17_textEdit")
        self.gridLayout.addWidget(self.saturday_17_textEdit, 10, 6, 1, 1)
        self.sunday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_11_textEdit.setSizePolicy(sizePolicy)
        self.sunday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_11_textEdit.setObjectName("sunday_11_textEdit")
        self.gridLayout.addWidget(self.sunday_11_textEdit, 5, 7, 1, 1)
        self.gym_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.gym_edit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.gym_edit.setInputMask("")
        self.gym_edit.setText("")
        self.gym_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gym_edit.setObjectName("gym_edit")
        self.gym_edit.textChanged.connect(self.check_inputs)
        self.gridLayout.addWidget(self.gym_edit, 2, 3, 1, 2)
        self.monday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_12_textEdit.setSizePolicy(sizePolicy)
        self.monday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_12_textEdit.setObjectName("monday_12_textEdit")
        self.gridLayout.addWidget(self.monday_12_textEdit, 6, 1, 1, 1)
        self.tuesday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_10_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_10_textEdit.setObjectName("tuesday_10_textEdit")
        self.gridLayout.addWidget(self.tuesday_10_textEdit, 4, 2, 1, 1)
        self.monday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.monday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setBold(True)
        font.setWeight(75)
        self.monday_label.setFont(font)
        self.monday_label.setObjectName("monday_label")
        self.gridLayout.addWidget(self.monday_label, 3, 1, 1, 1)
        self.tuesday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_12_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_12_textEdit.setObjectName("tuesday_12_textEdit")
        self.gridLayout.addWidget(self.tuesday_12_textEdit, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.thursday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.thursday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.thursday_label.setObjectName("thursday_label")
        self.gridLayout.addWidget(self.thursday_label, 3, 4, 1, 1)
        self.sunday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.sunday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.sunday_label.setObjectName("sunday_label")
        self.gridLayout.addWidget(self.sunday_label, 3, 7, 1, 1)
        self.saturday_10_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_10_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_10_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_10_textEdit.setSizePolicy(sizePolicy)
        self.saturday_10_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_10_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_10_textEdit.setObjectName("saturday_10_textEdit")
        self.gridLayout.addWidget(self.saturday_10_textEdit, 4, 6, 1, 1)
        self.friday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_11_textEdit.setSizePolicy(sizePolicy)
        self.friday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_11_textEdit.setObjectName("friday_11_textEdit")
        self.gridLayout.addWidget(self.friday_11_textEdit, 5, 5, 1, 1)
        self.saturday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_11_textEdit.setSizePolicy(sizePolicy)
        self.saturday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_11_textEdit.setObjectName("saturday_11_textEdit")
        self.gridLayout.addWidget(self.saturday_11_textEdit, 5, 6, 1, 1)
        self.tuesday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_11_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_11_textEdit.setObjectName("tuesday_11_textEdit")
        self.gridLayout.addWidget(self.tuesday_11_textEdit, 5, 2, 1, 1)
        self.saturday_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.saturday_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.saturday_label.setObjectName("saturday_label")
        self.gridLayout.addWidget(self.saturday_label, 3, 6, 1, 1)
        self.thursday_11_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_11_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_11_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_11_textEdit.setSizePolicy(sizePolicy)
        self.thursday_11_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_11_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_11_textEdit.setObjectName("thursday_11_textEdit")
        self.gridLayout.addWidget(self.thursday_11_textEdit, 5, 4, 1, 1)
        self.wednesday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_17_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_17_textEdit.setObjectName("wednesday_17_textEdit")
        self.gridLayout.addWidget(self.wednesday_17_textEdit, 10, 3, 1, 1)
        self.dinner_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setBold(True)
        font.setWeight(75)
        self.dinner_label.setFont(font)
        self.dinner_label.setStyleSheet("border-radius: 5%;")
        self.dinner_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dinner_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.dinner_label.setScaledContents(False)
        self.dinner_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dinner_label.setObjectName("dinner_label")
        self.gridLayout.addWidget(self.dinner_label, 8, 1, 1, 7)
        self.tuesday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_18_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_18_textEdit.setObjectName("tuesday_18_textEdit")
        self.gridLayout.addWidget(self.tuesday_18_textEdit, 11, 2, 1, 1)
        self.monday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_17_textEdit.setSizePolicy(sizePolicy)
        self.monday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_17_textEdit.setObjectName("monday_17_textEdit")
        self.gridLayout.addWidget(self.monday_17_textEdit, 10, 1, 1, 1)
        self.thursday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_13_textEdit.setSizePolicy(sizePolicy)
        self.thursday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_13_textEdit.setObjectName("thursday_13_textEdit")
        self.gridLayout.addWidget(self.thursday_13_textEdit, 7, 4, 1, 1)
        self.tuesday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_17_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_17_textEdit.setObjectName("tuesday_17_textEdit")
        self.gridLayout.addWidget(self.tuesday_17_textEdit, 10, 2, 1, 1)
        self.monday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_16_textEdit.setSizePolicy(sizePolicy)
        self.monday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_16_textEdit.setObjectName("monday_16_textEdit")
        self.gridLayout.addWidget(self.monday_16_textEdit, 9, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_18.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 11, 0, 1, 1)
        self.friday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_13_textEdit.setSizePolicy(sizePolicy)
        self.friday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_13_textEdit.setObjectName("friday_13_textEdit")
        self.gridLayout.addWidget(self.friday_13_textEdit, 7, 5, 1, 1)
        self.wednesday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_16_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_16_textEdit.setObjectName("wednesday_16_textEdit")
        self.gridLayout.addWidget(self.wednesday_16_textEdit, 9, 3, 1, 1)
        self.monday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_13_textEdit.setSizePolicy(sizePolicy)
        self.monday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_13_textEdit.setObjectName("monday_13_textEdit")
        self.gridLayout.addWidget(self.monday_13_textEdit, 7, 1, 1, 1)
        self.tuesday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_13_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_13_textEdit.setObjectName("tuesday_13_textEdit")
        self.gridLayout.addWidget(self.tuesday_13_textEdit, 7, 2, 1, 1)
        self.tuesday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tuesday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.tuesday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.tuesday_16_textEdit.setSizePolicy(sizePolicy)
        self.tuesday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.tuesday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.tuesday_16_textEdit.setObjectName("tuesday_16_textEdit")
        self.gridLayout.addWidget(self.tuesday_16_textEdit, 9, 2, 1, 1)
        self.thursday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_16_textEdit.setSizePolicy(sizePolicy)
        self.thursday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_16_textEdit.setObjectName("thursday_16_textEdit")
        self.gridLayout.addWidget(self.thursday_16_textEdit, 9, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_16.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 9, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_13.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.monday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.monday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.monday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.monday_18_textEdit.setSizePolicy(sizePolicy)
        self.monday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.monday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.monday_18_textEdit.setObjectName("monday_18_textEdit")
        self.gridLayout.addWidget(self.monday_18_textEdit, 11, 1, 1, 1)
        self.saturday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_12_textEdit.setSizePolicy(sizePolicy)
        self.saturday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_12_textEdit.setObjectName("saturday_12_textEdit")
        self.gridLayout.addWidget(self.saturday_12_textEdit, 6, 6, 1, 1)
        self.saturday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_13_textEdit.setSizePolicy(sizePolicy)
        self.saturday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_13_textEdit.setObjectName("saturday_13_textEdit")
        self.gridLayout.addWidget(self.saturday_13_textEdit, 7, 6, 1, 1)
        self.friday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_12_textEdit.setSizePolicy(sizePolicy)
        self.friday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_12_textEdit.setObjectName("friday_12_textEdit")
        self.gridLayout.addWidget(self.friday_12_textEdit, 6, 5, 1, 1)
        self.thursday_12_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_12_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_12_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_12_textEdit.setSizePolicy(sizePolicy)
        self.thursday_12_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_12_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_12_textEdit.setObjectName("thursday_12_textEdit")
        self.gridLayout.addWidget(self.thursday_12_textEdit, 6, 4, 1, 1)
        self.wednesday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_13_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_13_textEdit.setObjectName("wednesday_13_textEdit")
        self.gridLayout.addWidget(self.wednesday_13_textEdit, 7, 3, 1, 1)
        self.thursday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_17_textEdit.setSizePolicy(sizePolicy)
        self.thursday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_17_textEdit.setObjectName("thursday_17_textEdit")
        self.gridLayout.addWidget(self.thursday_17_textEdit, 10, 4, 1, 1)
        self.friday_17_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_17_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_17_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_17_textEdit.setSizePolicy(sizePolicy)
        self.friday_17_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_17_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_17_textEdit.setObjectName("friday_17_textEdit")
        self.gridLayout.addWidget(self.friday_17_textEdit, 10, 5, 1, 1)
        self.sunday_13_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_13_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_13_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_13_textEdit.setSizePolicy(sizePolicy)
        self.sunday_13_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_13_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_13_textEdit.setObjectName("sunday_13_textEdit")
        self.gridLayout.addWidget(self.sunday_13_textEdit, 7, 7, 1, 1)
        self.saturday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saturday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.saturday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.saturday_16_textEdit.setSizePolicy(sizePolicy)
        self.saturday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.saturday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.saturday_16_textEdit.setObjectName("saturday_16_textEdit")
        self.gridLayout.addWidget(self.saturday_16_textEdit, 9, 6, 1, 1)
        self.sunday_16_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sunday_16_textEdit.sizePolicy().hasHeightForWidth())
        self.sunday_16_textEdit.setStyleSheet("border-radius: 5%;")
        self.sunday_16_textEdit.setSizePolicy(sizePolicy)
        self.sunday_16_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.sunday_16_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.sunday_16_textEdit.setObjectName("sunday_16_textEdit")
        self.gridLayout.addWidget(self.sunday_16_textEdit, 9, 7, 1, 1)
        self.thursday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.thursday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.thursday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.thursday_18_textEdit.setSizePolicy(sizePolicy)
        self.thursday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.thursday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.thursday_18_textEdit.setObjectName("thursday_18_textEdit")
        self.gridLayout.addWidget(self.thursday_18_textEdit, 11, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_17.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_17.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 10, 0, 1, 1)
        self.friday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.friday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.friday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.friday_18_textEdit.setSizePolicy(sizePolicy)
        self.friday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.friday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.friday_18_textEdit.setObjectName("friday_18_textEdit")
        self.gridLayout.addWidget(self.friday_18_textEdit, 11, 5, 1, 1)
        self.wednesday_18_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.wednesday_18_textEdit.sizePolicy().hasHeightForWidth())
        self.wednesday_18_textEdit.setStyleSheet("border-radius: 5%;")
        self.wednesday_18_textEdit.setSizePolicy(sizePolicy)
        self.wednesday_18_textEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.wednesday_18_textEdit.setMaximumSize(QtCore.QSize(1000, 400))
        self.wednesday_18_textEdit.setObjectName("wednesday_18_textEdit")
        self.gridLayout.addWidget(self.wednesday_18_textEdit, 11, 3, 1, 1)
        self.add_trainer_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_trainer_btn.setObjectName("add_trainer_btn")
        self.add_trainer_btn.clicked.connect(self.add_trainer_btn_was_clicked)
        self.gridLayout.addWidget(self.add_trainer_btn, 16, 0, 1, 2)
        self.trainer_list_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.trainer_list_line_edit.setObjectName("trainer_list_line_edit")
        self.gridLayout.addWidget(self.trainer_list_line_edit, 15, 0, 1, 4)
        self.delete_trainer_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_trainer_btn.setObjectName("delete_trainer_btn")
        self.delete_trainer_btn.clicked.connect(self.remove_trainer_btn_was_clicked)
        self.gridLayout.addWidget(self.delete_trainer_btn, 16, 2, 1, 2)
        self.add_workout_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_workout_btn.setObjectName("add_workout_btn")
        self.add_workout_btn.clicked.connect(self.add_workout_btn_was_clicked)
        self.gridLayout.addWidget(self.add_workout_btn, 16, 4, 1, 2)
        self.delete_workout_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_workout_btn.setObjectName("delete_workout_btn")
        self.delete_workout_btn.clicked.connect(self.remove_workout_btn_was_clicked)
        self.gridLayout.addWidget(self.delete_workout_btn, 16, 6, 1, 2)
        self.workout_list_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.workout_list_line_edit.setObjectName("workout_list_line_edit")
        self.gridLayout.addWidget(self.workout_list_line_edit, 15, 4, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schedule Creator"))
        self.done_btn.setText(_translate("MainWindow", "Готово"))
        self.label_20.setText(_translate("MainWindow", "20:00-21:00"))
        self.label_19.setText(_translate("MainWindow", "19:00-20:00"))
        __sortingEnabled = self.trainer_list.isSortingEnabled()
        self.trainer_list.setSortingEnabled(False)
        self.trainer_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.workout_list.isSortingEnabled()
        self.workout_list.setSortingEnabled(False)
        self.workout_list.setSortingEnabled(__sortingEnabled)
        self.label_12.setText(_translate("MainWindow", "12:00-13:00"))
        self.tuesday_label.setText(_translate("MainWindow", "Вторник"))
        self.friday_label.setText(_translate("MainWindow", "Пятница"))
        self.wednesday_label.setText(_translate("MainWindow", "Среда"))
        self.label_10.setText(_translate("MainWindow", "10:00-11:00"))
        self.label_11.setText(_translate("MainWindow", "11:00-12:00"))
        self.month_edit.setPlaceholderText(_translate("MainWindow", "Введите месяц"))
        self.gym_edit.setPlaceholderText(_translate("MainWindow", "Зал 1 или Зал 2"))
        self.monday_label.setText(_translate("MainWindow", "Понедельник"))
        self.thursday_label.setText(_translate("MainWindow", "Четверг"))
        self.sunday_label.setText(_translate("MainWindow", "Воскресенье"))
        self.saturday_label.setText(_translate("MainWindow", "Суббота"))
        self.dinner_label.setText(_translate("MainWindow", "Обед"))
        self.label_18.setText(_translate("MainWindow", "18:00-19:00"))
        self.label_16.setText(_translate("MainWindow", "16:00-17:00"))
        self.label_13.setText(_translate("MainWindow", "13:00-14:00"))
        self.label_17.setText(_translate("MainWindow", "17:00-18:00"))
        self.add_trainer_btn.setText(_translate("MainWindow", "Добавить"))
        self.trainer_list_line_edit.setPlaceholderText(_translate("MainWindow", "Введите имя тренера"))
        self.delete_trainer_btn.setText(_translate("MainWindow", "Удалить"))
        self.add_workout_btn.setText(_translate("MainWindow", "Добавить"))
        self.delete_workout_btn.setText(_translate("MainWindow", "Удалить"))
        self.workout_list_line_edit.setPlaceholderText(_translate("MainWindow", "Введите название тренировки"))
        
